server:
  port: 8081

spring:
  application:
    name: stockwolf-inventory

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  introspection:
    server:
      baseUrl: http://${INTROSPECTION_HOST}:${INTROSPECTION_PORT}
    api: ${INTROSPECTION_API}
